const DUMMY = 'DUMMY'

export function dummy(value = ''): { type: typeof DUMMY, value: string } {
  return {
    type: DUMMY,
    value
  }
}

// NAV STATE
export const NAV_NAVIGATION_UPDATED: 'NAV_NAVIGATION_UPDATED' = 'NAV_NAVIGATION_UPDATED'
export const NAV_AUTH_UPDATED: 'NAV_AUTH_UPDATED' = 'NAV_AUTH_UPDATED'


// ENV STATE
export const ENV_STATE_ATTACH: 'ENV_STATE_ATTACH' = 'ENV_STATE_ATTACH'
export const ENV_STATE_ATTACHED: 'ENV_STATE_ATTACHED' = 'ENV_STATE_ATTACHED'
export const ENV_STATE_SIGN_IN: 'ENV_STATE_SIGN_IN' = 'ENV_STATE_SIGN_IN'
export const ENV_STATE_SIGNED: 'ENV_STATE_SIGNED' = 'ENV_STATE_SIGNED'
export const ENV_STATE_CUSTOMER_CTX_UPDATE: 'ENV_STATE_CUSTOMER_CTX_UPDATE' = 'ENV_STATE_CUSTOMER_CTX_UPDATE'
export const ENV_STATE_NAVIGATION_UPDATE: 'ENV_STATE_NAVIGATION_UPDATE' = 'ENV_STATE_NAVIGATION_UPDATE'
export const ENV_STATE_CUSTOMER_CTX_UPDATED: 'ENV_STATE_CUSTOMER_CTX_UPDATED' = 'ENV_STATE_CUSTOMER_CTX_UPDATED'
export const ENV_STATE_SET_WORKSPACE: 'ENV_STATE_SET_WORKSPACE' = 'ENV_STATE_SET_WORKSPACE'
export const ENV_MESSAGE_RECEIVED: 'ENV_MESSAGE_RECEIVED' = 'ENV_MESSAGE_RECEIVED'

// RELATIONS
export const RELATION_CLEAN: 'RELATION_CLEAN' = 'RELATION_CLEAN'
export const RELATION_FETCH: 'RELATION_FETCH' = 'RELATION_FETCH'
export const RELATION_FETCH_STARTED: 'RELATION_FETCH_STARTED' = 'RELATION_FETCH_STARTED'
export const RELATION_FETCH_COMPLETED: 'RELATION_FETCH_COMPLETED' = 'RELATION_FETCH_COMPLETED'
export const RELATION_SELECT: 'RELATION_SELECT' = 'RELATION_SELECT'

// POINTS
export const POINT_CLEAN: 'POINT_CLEAN' = 'POINT_CLEAN'
export const POINT_EXTRA_ENV_UPDATED: 'POINT_EXTRA_ENV_UPDATED' = 'POINT_EXTRA_ENV_UPDATED'
export const POINT_FETCH_START: 'POINT_FETCH_START' = 'POINT_FETCH_START'
export const POINT_FETCH: 'POINT_FETCH' = 'POINT_FETCH'
export const POINT_FILLED: 'POINT_FILLED' = 'POINT_FILLED'
export const POINT_SELECT: 'POINT_SELECT' = 'POINT_SELECT'

// PROPERTY SEARCH
export const PROPERTY_SEARCH_CLEAN: 'PROPERTY_SEARCH_CLEAN' = 'PROPERTY_SEARCH_CLEAN'
export const PROPERTY_SEARCH_FETCH_START: 'PROPERTY_SEARCH_FETCH_START' = 'PROPERTY_SEARCH_FETCH_START'
export const PROPERTY_SEARCH_FETCH: 'PROPERTY_SEARCH_FETCH' = 'PROPERTY_SEARCH_FETCH'
export const PROPERTY_SEARCH_FILLED: 'PROPERTY_SEARCH_FILLED' = 'PROPERTY_SEARCH_FILLED'

// EXCURSION TAG
export const EXCURSION_TAG_CLEAN: 'EXCURSION_TAG_CLEAN' = 'EXCURSION_TAG_CLEAN'
export const EXCURSION_TAG_FETCH_START: 'EXCURSION_TAG_FETCH_START' = 'EXCURSION_TAG_FETCH_START'
export const EXCURSION_TAG_FETCH: 'EXCURSION_TAG_FETCH' = 'EXCURSION_TAG_FETCH'
export const EXCURSION_TAG_FILLED: 'EXCURSION_TAG_FILLED' = 'EXCURSION_TAG_FILLED'
export const EXCURSION_TAG_EXTRA_ENV_UPDATED: 'EXCURSION_TAG_EXTRA_ENV_UPDATED' = 'EXCURSION_TAG_EXTRA_ENV_UPDATED'

// EXCURSION SEARCH
export const EXCURSION_SEARCH_CLEAN: 'EXCURSION_SEARCH_CLEAN' = 'EXCURSION_SEARCH_CLEAN'
export const EXCURSION_SEARCH_FETCH_START: 'EXCURSION_SEARCH_FETCH_START' = 'EXCURSION_SEARCH_FETCH_START'
export const EXCURSION_SEARCH_FETCH: 'EXCURSION_SEARCH_FETCH' = 'EXCURSION_SEARCH_FETCH'
export const EXCURSION_SEARCH_FILLED: 'EXCURSION_SEARCH_FILLED' = 'EXCURSION_SEARCH_FILLED'

// SEARCH SESSION
export const PLANNER_SESSION_CLEAN: 'PLANNER_SESSION_CLEAN' = 'PLANNER_SESSION_CLEAN'
export const PLANNER_SESSION_FETCH: 'PLANNER_SESSION_FETCH' = 'PLANNER_SESSION_FETCH'
export const PLANNER_SESSION_FETCH_COMPLETED: 'PLANNER_SESSION_FETCH_COMPLETED' = 'PLANNER_SESSION_FETCH_COMPLETED'
export const PLANNER_SESSION_CREATE_FORM_TOGGLE: 'PLANNER_SESSION_CREATE_FORM_TOGGLE' = 'PLANNER_SESSION_CREATE_FORM_TOGGLE'
export const PLANNER_SESSION_CREATE: 'PLANNER_SESSION_CREATE' = 'PLANNER_SESSION_CREATE'
export const PLANNER_SESSION_REMOVE: 'PLANNER_SESSION_REMOVE' = 'PLANNER_SESSION_REMOVE'
export const PLANNER_SESSION_REMOVED: 'PLANNER_SESSION_REMOVED' = 'PLANNER_SESSION_REMOVED'
export const PLANNER_SESSION_SELECT: 'PLANNER_SESSION_SELECT' = 'PLANNER_SESSION_SELECT'
export const PLANNER_SESSION_SELECTED: 'PLANNER_SESSION_SELECTED' = 'PLANNER_SESSION_SELECTED'
export const PLANNER_SESSION_CREATED: 'PLANNER_SESSION_CREATED' = 'PLANNER_SESSION_CREATED'
export const PLANNER_SESSION_UPDATE: 'PLANNER_SESSION_UPDATE' = 'PLANNER_SESSION_UPDATE'
export const PLANNER_SESSION_HEAD_UPDATED: 'PLANNER_SESSION_HEAD_UPDATED' = 'PLANNER_SESSION_HEAD_UPDATED'
export const PLANNER_SESSION_POINT_CREATE: 'PLANNER_SESSION_POINT_CREATE' = 'PLANNER_SESSION_POINT_CREATE'
export const PLANNER_SESSION_SET_BOOKING_STEP: 'PLANNER_SESSION_SET_BOOKING_STEP' = 'PLANNER_SESSION_SET_BOOKING_STEP'
export const PLANNER_SESSION_POINT_SELECT: 'PLANNER_SESSION_POINT_SELECT' = 'PLANNER_SESSION_POINT_SELECT'
export const PLANNER_SESSION_POINT_REMOVE: 'PLANNER_SESSION_POINT_REMOVE' = 'PLANNER_SESSION_POINT_REMOVE'
export const PLANNER_SESSION_PROPERTY_FILTER_SET_STOP: 'PLANNER_SESSION_PROPERTY_FILTER_SET_STOP' = 'PLANNER_SESSION_PROPERTY_FILTER_SET_STOP'
export const PLANNER_SESSION_PROPERTY_FILTER_SET_STAR: 'PLANNER_SESSION_PROPERTY_FILTER_SET_STAR' = 'PLANNER_SESSION_PROPERTY_FILTER_SET_STAR'
export const PLANNER_SESSION_PROPERTY_FILTER_SET_NAME: 'PLANNER_SESSION_PROPERTY_FILTER_SET_NAME' = 'PLANNER_SESSION_PROPERTY_FILTER_SET_NAME'
export const PLANNER_SESSION_PROPERTY_FILTER_SET_AMENITIES: 'PLANNER_SESSION_PROPERTY_FILTER_SET_AMENITIES' = 'PLANNER_SESSION_PROPERTY_FILTER_SET_AMENITIES'
export const PLANNER_SESSION_PROPERTY_FILTER_SET_BOARDINGS: 'PLANNER_SESSION_PROPERTY_FILTER_SET_BOARDINGS' = 'PLANNER_SESSION_PROPERTY_FILTER_SET_BOARDINGS'
export const PLANNER_SESSION_PROPERTY_FILTER_SET_FACILITIES: 'PLANNER_SESSION_PROPERTY_FILTER_SET_FACILITIES' = 'PLANNER_SESSION_PROPERTY_FILTER_SET_FACILITIES'
export const PLANNER_SESSION_PROPERTY_FILTER_SET_MEDICALS: 'PLANNER_SESSION_PROPERTY_FILTER_SET_MEDICALS' = 'PLANNER_SESSION_PROPERTY_FILTER_SET_MEDICALS'
export const PLANNER_SESSION_PROPERTY_FILTER_SET_INDICATIONS: 'PLANNER_SESSION_PROPERTY_FILTER_SET_INDICATIONS' = 'PLANNER_SESSION_PROPERTY_FILTER_SET_INDICATIONS'
export const PLANNER_SESSION_PROPERTY_FILTER_SET_THERAPIES: 'PLANNER_SESSION_PROPERTY_FILTER_SET_THERAPIES' = 'PLANNER_SESSION_PROPERTY_FILTER_SET_THERAPIES'
export const PLANNER_SESSION_PROPERTY_FILTER_SET_PRICE: 'PLANNER_SESSION_PROPERTY_FILTER_SET_PRICE' = 'PLANNER_SESSION_PROPERTY_FILTER_SET_PRICE'
export const PLANNER_SESSION_PROPERTY_FILTER_RESET: 'PLANNER_SESSION_PROPERTY_FILTER_RESET' = 'PLANNER_SESSION_PROPERTY_FILTER_RESET'
export const PLANNER_SESSION_PROPERTY_SET_PRICE_VIEW_MODE: 'PLANNER_SESSION_PROPERTY_SET_PRICE_VIEW_MODE' = 'PLANNER_SESSION_PROPERTY_SET_PRICE_VIEW_MODE'
export const PLANNER_SESSION_PROPERTY_SET_MAX_ITEMS: 'PLANNER_SESSION_PROPERTY_SET_MAX_ITEMS' = 'PLANNER_SESSION_PROPERTY_SET_MAX_ITEMS'
export const PLANNER_SESSION_POINT_PROPERTY_ACCOMMODATION_VARIANT_ADD: 'PLANNER_SESSION_POINT_PROPERTY_ACCOMMODATION_VARIANT_ADD' = 'PLANNER_SESSION_POINT_PROPERTY_ACCOMMODATION_VARIANT_ADD'
export const PLANNER_SESSION_POINT_PROPERTY_ACCOMMODATION_VARIANT_REMOVE: 'PLANNER_SESSION_POINT_PROPERTY_ACCOMMODATION_VARIANT_REMOVE' = 'PLANNER_SESSION_POINT_PROPERTY_ACCOMMODATION_VARIANT_REMOVE'
export const PLANNER_SESSION_POINT_PROPERTY_ACCOMMODATION_VARIANT_SELECT: 'PLANNER_SESSION_POINT_PROPERTY_ACCOMMODATION_VARIANT_SELECT' = 'PLANNER_SESSION_POINT_PROPERTY_ACCOMMODATION_VARIANT_SELECT'

export const PLANNER_SESSION_EXCURSION_FILTER_SET_NAME: 'PLANNER_SESSION_EXCURSION_FILTER_SET_NAME' = 'PLANNER_SESSION_EXCURSION_FILTER_SET_NAME'
export const PLANNER_SESSION_EXCURSION_FILTER_SET_PRICE: 'PLANNER_SESSION_EXCURSION_FILTER_SET_PRICE' = 'PLANNER_SESSION_EXCURSION_FILTER_SET_PRICE'
export const PLANNER_SESSION_EXCURSION_FILTER_SET_DATES: 'PLANNER_SESSION_EXCURSION_FILTER_SET_DATES' = 'PLANNER_SESSION_EXCURSION_FILTER_SET_DATES'
export const PLANNER_SESSION_EXCURSION_FILTER_SET_TAGS: 'PLANNER_SESSION_EXCURSION_FILTER_SET_TAGS' = 'PLANNER_SESSION_EXCURSION_FILTER_SET_TAGS'
export const PLANNER_SESSION_EXCURSION_FILTER_RESET: 'PLANNER_SESSION_EXCURSION_FILTER_RESET' = 'PLANNER_SESSION_EXCURSION_FILTER_RESET'
export const PLANNER_SESSION_EXCURSION_SET_MAX_ITEMS: 'PLANNER_SESSION_EXCURSION_SET_MAX_ITEMS' = 'PLANNER_SESSION_EXCURSION_SET_MAX_ITEMS'
export const PLANNER_SESSION_EXCURSION_SET_EVENT_DATES: 'PLANNER_SESSION_EXCURSION_SET_EVENT_DATES' = 'PLANNER_SESSION_EXCURSION_SET_EVENT_DATES'
export const PLANNER_SESSION_EXCURSION_SET_EXCURSION_DATES: 'PLANNER_SESSION_EXCURSION_SET_EXCURSION_DATES' = 'PLANNER_SESSION_EXCURSION_SET_EXCURSION_DATES'
export const PLANNER_SESSION_EXCURSION_UPDATE_EXCURSION_DATE: 'PLANNER_SESSION_EXCURSION_UPDATE_EXCURSION_DATE' = 'PLANNER_SESSION_EXCURSION_UPDATE_EXCURSION_DATE'
export const PLANNER_SESSION_POINT_EXCURSION_VARIANT_ADD: 'PLANNER_SESSION_POINT_EXCURSION_VARIANT_ADD' = 'PLANNER_SESSION_POINT_EXCURSION_VARIANT_ADD'
export const PLANNER_SESSION_POINT_EXCURSION_VARIANT_REMOVE: 'PLANNER_SESSION_POINT_EXCURSION_VARIANT_REMOVE' = 'PLANNER_SESSION_POINT_EXCURSION_VARIANT_REMOVE'
export const PLANNER_SESSION_POINT_EXCURSION_VARIANT_SELECT: 'PLANNER_SESSION_POINT_EXCURSION_VARIANT_SELECT' = 'PLANNER_SESSION_POINT_EXCURSION_VARIANT_SELECT'



export const PLANNER_SESSION_TOGGLE_PREVIEW: 'PLANNER_SESSION_TOGGLE_PREVIEW' = 'PLANNER_SESSION_TOGGLE_PREVIEW'
export const PLANNER_SESSION_CLIENT_SET_FIRST_NAME: 'PLANNER_SESSION_CLIENT_SET_FIRST_NAME' = 'PLANNER_SESSION_CLIENT_SET_FIRST_NAME'
export const PLANNER_SESSION_CLIENT_SET_LAST_NAME: 'PLANNER_SESSION_CLIENT_SET_LAST_NAME' = 'PLANNER_SESSION_CLIENT_SET_LAST_NAME'
export const PLANNER_SESSION_CLIENT_SET_BIRTH_DAY: 'PLANNER_SESSION_CLIENT_SET_BIRTH_DAY' = 'PLANNER_SESSION_CLIENT_SET_BIRTH_DAY'
export const PLANNER_SESSION_CLIENT_SET_GENDER: 'PLANNER_SESSION_CLIENT_SET_GENDER' = 'PLANNER_SESSION_CLIENT_SET_GENDER'
export const PLANNER_SESSION_CLIENT_SET_PASSPORT_SERIAL: 'PLANNER_SESSION_CLIENT_SET_PASSPORT_SERIAL' = 'PLANNER_SESSION_CLIENT_SET_PASSPORT_SERIAL'
export const PLANNER_SESSION_CLIENT_SET_PASSPORT_NUMBER: 'PLANNER_SESSION_CLIENT_SET_PASSPORT_NUMBER' = 'PLANNER_SESSION_CLIENT_SET_PASSPORT_NUMBER'
export const PLANNER_SESSION_CLIENT_SET_PASSPORT_EXPIRED: 'PLANNER_SESSION_CLIENT_SET_PASSPORT_EXPIRED' = 'PLANNER_SESSION_CLIENT_SET_PASSPORT_EXPIRED'
export const PLANNER_SESSION_CLIENT_SET_PASSPORT_STATE: 'PLANNER_SESSION_CLIENT_SET_PASSPORT_STATE' = 'PLANNER_SESSION_CLIENT_SET_PASSPORT_STATE'
export const PLANNER_SESSION_CLIENT_CLEAN: 'PLANNER_SESSION_CLIENT_CLEAN' = 'PLANNER_SESSION_CLIENT_CLEAN'

// AMENITY

export const AMENITY_CLEAN: 'AMENITY_CLEAN' = 'AMENITY_CLEAN'
export const AMENITY_FETCH_START: 'AMENITY_FETCH_START' = 'AMENITY_FETCH_START'
export const AMENITY_FETCH: 'AMENITY_FETCH' = 'AMENITY_FETCH'
export const AMENITY_FILLED: 'AMENITY_FILLED' = 'AMENITY_FILLED'
export const AMENITY_EXTRA_ENV_UPDATED: 'AMENITY_EXTRA_ENV_UPDATED' = 'AMENITY_EXTRA_ENV_UPDATED'

// FACILITY

export const FACILITY_CLEAN: 'FACILITY_CLEAN' = 'FACILITY_CLEAN'
export const FACILITY_FETCH_START: 'FACILITY_FETCH_START' = 'FACILITY_FETCH_START'
export const FACILITY_FETCH: 'FACILITY_FETCH' = 'FACILITY_FETCH'
export const FACILITY_FILLED: 'FACILITY_FILLED' = 'FACILITY_FILLED'
export const FACILITY_EXTRA_ENV_UPDATED: 'FACILITY_EXTRA_ENV_UPDATED' = 'FACILITY_EXTRA_ENV_UPDATED'

// THERAPY

export const THERAPY_CLEAN: 'THERAPY_CLEAN' = 'THERAPY_CLEAN'
export const THERAPY_FETCH_START: 'THERAPY_FETCH_START' = 'THERAPY_FETCH_START'
export const THERAPY_FETCH: 'THERAPY_FETCH' = 'THERAPY_FETCH'
export const THERAPY_FILLED: 'THERAPY_FILLED' = 'THERAPY_FILLED'
export const THERAPY_EXTRA_ENV_UPDATED: 'THERAPY_EXTRA_ENV_UPDATED' = 'THERAPY_EXTRA_ENV_UPDATED'

// INDICATIONS

export const INDICATION_CLEAN: 'INDICATION_CLEAN' = 'INDICATION_CLEAN'
export const INDICATION_FETCH_START: 'INDICATION_FETCH_START' = 'INDICATION_FETCH_START'
export const INDICATION_FETCH: 'INDICATION_FETCH' = 'INDICATION_FETCH'
export const INDICATION_FILLED: 'INDICATION_FILLED' = 'INDICATION_FILLED'
export const INDICATION_EXTRA_ENV_UPDATED: 'INDICATION_EXTRA_ENV_UPDATED' = 'INDICATION_EXTRA_ENV_UPDATED'

// PROPERTY PAGE

export const PROPERTY_SET: 'PROPERTY_SET' = 'PROPERTY_SET'
export const PROPERTY_CLEAN: 'PROPERTY_CLEAN' = 'PROPERTY_CLEAN'
export const PROPERTY_PRICE_FETCH: 'PROPERTY_PRICE_FETCH' = 'PROPERTY_PRICE_FETCH'
export const PROPERTY_PRICE_FETCH_START: 'PROPERTY_PRICE_FETCH_START' = 'PROPERTY_PRICE_FETCH_START'
export const PROPERTY_PRICE_FILLED: 'PROPERTY_PRICE_FILLED' = 'PROPERTY_PRICE_FILLED'
export const PROPERTY_DESCRIPTION_FETCH: 'PROPERTY_DESCRIPTION_FETCH' = 'PROPERTY_DESCRIPTION_FETCH'
export const PROPERTY_DESCRIPTION_FETCH_START: 'PROPERTY_DESCRIPTION_FETCH_START' = 'PROPERTY_DESCRIPTION_FETCH_START'
export const PROPERTY_DESCRIPTION_FILLED: 'PROPERTY_DESCRIPTION_FILLED' = 'PROPERTY_DESCRIPTION_FILLED'

// SHOPPING CART
export const CART_CREATE: 'CART_CREATE' = 'CART_CREATE'
export const CART_CREATED: 'CART_CREATED' = 'CART_CREATED'
export const CART_DROP: 'CART_DROP' = 'CART_DROP'
export const CART_LOCATION_ADD: 'CART_LOCATION_ADD' = 'CART_LOCATION_ADD'
export const CART_LOCATION_REMOVE: 'CART_LOCATION_REMOVE' = 'CART_LOCATION_REMOVE'
export const CART_ACCOMMODATION_ADD: 'CART_ACCOMMODATION_ADD' = 'CART_ACCOMMODATION_ADD'
export const CART_ACCOMMODATION_ADDED: 'CART_ACCOMMODATION_ADDED' = 'CART_ACCOMMODATION_ADDED'
export const CART_ACCOMMODATION_REMOVE: 'CART_ACCOMMODATION_REMOVE' = 'CART_ACCOMMODATION_REMOVE'
export const CART_MODIFY_CLIENT: 'CART_MODIFY_CLIENT' = 'CART_MODIFY_CLIENT'
export const CART_MODIFY_DATES: 'CART_MODIFY_DATES' = 'CART_MODIFY_DATES'
export const CART_MODIFY_NOTES: 'CART_MODIFY_NOTES' = 'CART_MODIFY_NOTES'
export const CART_SET_PREVIEW: 'CART_SET_PREVIEW' = 'CART_SET_PREVIEW'
