import { makeStyles } from '@material-ui/core/styles'
import { AppTheme } from '../../theme'

export const useStyles = makeStyles((theme: AppTheme) => ({
  root: {
    position: 'fixed',
    top: '3.3rem',
    right: '1rem',
    display: 'flex',
    flexFlow: 'column',
    justifyContent: 'center',
    alignContent: 'center',
    width: '22rem',
    paddingLeft: '1rem',
    paddingRight: '1rem',
    paddingBottom: '1rem',
    minHeight: '10rem',
    maxHeight: 'calc(100% - calc(3.3rem * 2))',
    backgroundColor: 'white',
    borderTop: `2px solid ${theme.cssEnv.palette.primary}`,
    borderLeft: 'solid 1px #f2f5fb',
    borderRight: 'solid 1px #f2f5fb',
    borderBottom: 'solid 1px #f2f5fb',
    boxShadow: '0 7px 8px 0 rgba(0, 0, 0, 0.1)',
    overflow: 'scroll',
    '& .view': {
      '& .title': {
        fontSize: '0.9rem',
        color: theme.cssEnv.palette.menuText,
        fontWeight: theme.cssEnv.typo.weightRegular,
        '& .location': {
          display: 'flex',
          width: '100%',
          fontSize: '0.8rem',
          fontWeight: theme.cssEnv.typo.weightMedium,
        },
      },
      '& .item': {
        display: 'flex',
        flexFlow: 'row nowrap',
        width: '100%',
        marginTop: '0.7rem',
        '& .title': {
          width: `calc(100% - 4rem)`,
          fontSize: '0.8rem',
          fontWeight: theme.cssEnv.typo.weightMedium,
          marginBottom: 'calc(0.7rem / 2)',
        },
        '& .price': {
          display: 'flex',
          justifyContent: 'flex-end',
          width: '4rem',
          fontSize: '0.8rem',
          fontWeight: theme.cssEnv.typo.weightRegular,
          color: theme.cssEnv.palette.primary,
        },
      },
      '& .description': {
        display: 'flex',
        flexFlow: 'row nowrap',
        width: '100%',
        '& .room': {
          display: 'flex',
          justifyContent: 'space-between',
          color: theme.cssEnv.palette.menuTextLight,
          fontSize: '.9rem',
          fontWeight: theme.cssEnv.typo.weightRegular,
          width: 'calc(100% - 4rem)',
        },
        '& .group': {
          display: 'flex',
          flexFlow: 'row',
          justifyContent: 'flex-end',
          alignItems: 'flex-start',
          width: '4rem',
          '& div': {
            width: '1.5rem',
            outline: 'none',
            border: 'none',
            cursor: 'pointer',
            userSelect: 'none',
          },
          '& i': {
            fontSize: '1rem',
            color: theme.cssEnv.palette.menuTextLight,
          },
          '& i::hover': {
            fontSize: '1.1rem',
            color: theme.cssEnv.palette.primary,
          },
        },
      },
    },
    '& .view::hover': {
      borderTop: `1px dotted ${theme.cssEnv.palette.menuTextLight}`,
      borderBottom: `1px dotted ${theme.cssEnv.palette.menuTextLight}`,
    },
    '& .action': {
      display: 'flex',
      flexFlow: 'row nowrap',
      alignSelf: 'center',
      justifyContent: 'flex-end',
      width: '100%',
      color: theme.cssEnv.palette.primary,
      paddingTop: '0.4rem',
      paddingBottom: '0.4rem',
      fontSize: '1.2rem',
      '& i': {
        fontSize: '1.1rem',
        fontWeight: theme.cssEnv.typo.weightMedium,
        cursor: 'pointer',
      },
    },
    '& .button': {
      display: 'flex',
      justifyContent: 'center',
      width: '100%',
      marginTop: '0.7rem',
      paddingTop: '0.7rem',
      paddingBottom: '0.7rem',
      backgroundColor: theme.cssEnv.palette.primary,
      border: 'none',
      cursor: 'pointer',
      outline: '0',
      userSelect: 'none',
      fontSize: '0.8rem',
      color: '#ffffff',
    },
  },
}))

export default useStyles