import { makeStyles } from '@material-ui/core/styles'
import { AppTheme } from '../../../../../theme'

export const useStyles = makeStyles((theme: AppTheme) => ({
  root: {
    position: 'absolute',
    overflow: 'scroll',
    display: 'flex',
    flexFlow: 'row',
    justifyContent: 'stretch',
    height: '15rem',
    margin: 0,
    padding: 0,
    backgroundColor: 'white',
    boxShadow: '0 7px 8px 0 rgba(0, 0, 0, 0.1)',
    zIndex: 1,
    '& .left': {
      display: 'flex',
      flexFlow: 'column',
      justifyContent: 'space-between',
      alignItems: 'center',
      '& .item': {
        cursor: 'pointer',
        display: 'flex',
        alignItems: 'baseline',
        width: 'calc(100% - 0.1rem)',
        padding: '.5rem',
        fontSize: '0.9rem',
        fontWeight: theme.cssEnv.typo.weightRegular,
        color: theme.cssEnv.palette.subMenu,
        '& span': {
          marginLeft: '2rem',
          fontSize: '0.8rem',
          color: theme.cssEnv.palette.subMenu,
        },
      },
      '& .active': {
        fontSize: '.9rem',
        fontWeight: '500',
        color: theme.cssEnv.palette.text,
        width: 'calc(100% - 1rem)',
        '& span': {
          marginLeft: '2rem',
          fontSize: '0.8rem',
          color: theme.cssEnv.palette.menuText,
        },
      },
    },
    '& .full': {
      flexGrow: 1,
    },
    '& .half': {
      width: '50%',
    },
    '& .right': {
      display: 'flex',
      flexFlow: 'row wrap',
      justifyContent: 'space-between',
      alignItems: 'baseline',
      width: '50%',
      borderLeft: `0.05rem solid ${theme.cssEnv.palette.menuTextLight}`,
      '& .minus': {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        width: '2rem',
        padding: '0.2rem',
        fontSize: '1.5rem',
        fontWeight: theme.cssEnv.typo.weightMedium,
        color: theme.cssEnv.palette.secondary,
        cursor: 'pointer',
      },
      '& .plus': {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        width: '2rem',
        padding: '0.2rem',
        fontSize: '1.5rem',
        fontWeight: theme.cssEnv.typo.weightMedium,
        color: theme.cssEnv.palette.secondary,
        cursor: 'pointer',
      },
      '& .info': {
        display: 'flex',
        width: 'calc(100% - 10rem)',
        fontSize: '0.8rem',
        fontWeight: theme.cssEnv.typo.weightRegular,
        color: theme.cssEnv.palette.menuText,
      },
      '& .action': {
        display: 'flex',
        width: '100%',
        flexGrow: '1',
        justifyContent: 'center',
        alignItems: 'center',
        '& .button': {
          width: '80%',
          height: '2rem',
          backgroundColor: theme.cssEnv.palette.primaryDark,
          color: '#ffffff',
          fontSize: '1rem',
          borderColor: theme.cssEnv.palette.primary,
        },
      },
    },
  },
  normal: {
    width: '14.8rem',
  },
  wide: {
    width: '30rem',
  },
  title: {
    display: 'flex',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: '0.5rem',
    paddingBottom: '0.5rem',
    fontSize: '1rem',
    fontWeight: theme.cssEnv.typo.weightRegular,
    color: theme.cssEnv.palette.menuText,
    backgroundColor: theme.cssEnv.palette.pageBackgroundDarker,
  },
  age: {
    display: 'flex',
    width: '100%',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '1rem',
    borderBottom: `0.15rem solid ${theme.cssEnv.palette.pageBackground}`,
  },
}))

export default useStyles