import { makeStyles } from '@material-ui/core/styles'
import { AppTheme } from '../../../../theme'

export const useStyles = makeStyles((theme: AppTheme) => ({
  root: {
    display: 'flex',
    flexFlow: 'column',
    justifyContent: 'space-between',
    width: 'calc(100% - 1rem)',
    height: 'calc(100% - 1rem)',
    border: `solid 1px ${theme.cssEnv.palette.menuTextExtraLight}`,
    padding: '0.5rem',
    '& .price': {
      display: 'flex',
      flexFlow: 'row nowrap',
      justifyContent: 'flex-end',
      alignItems: 'center',
      width: '100%',
      height: '100%',
      fontSize: '2rem',
      fontWeight: theme.cssEnv.typo.weightRegular,
      '& .discount': {
        display: 'flex',
        flexFlow: 'row',
        justifyContent: 'flex-start',
        alignItems: 'baseline',
        width: '50%',
        fontSize: '2rem',
        fontWeight: theme.cssEnv.typo.weightLight,
        color: theme.cssEnv.palette.secondaryLight,
        textDecoration: 'line-through',
      },
      '& .amount': {
        display: 'flex',
        flexFlow: 'row',
        flexGrow: '1',
        justifyContent: 'flex-end',
        alignItems: 'baseline',
        width: '50%',
        color: theme.cssEnv.palette.secondary,
        '& .currency': {
          fontWeight: theme.cssEnv.typo.weightLight,
        },
      },
      '& .amount-stop': {
        display: 'flex',
        flexFlow: 'row',
        flexGrow: 1,
        justifyContent: 'center',
        width: '50%',
        color: theme.cssEnv.palette.menuTextLight,
      },
      '& .stop': {
        display: 'flex',
        flexFlow: 'row',
        justifyContent: 'center',
        alignItems: 'baseline',
        width: '50%',
        fontSize: '0.8rem',
        color: 'red',
      },
    },
    '& .button':
      {
        display: 'flex',
        flexFlow: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
        height: '2rem',
        backgroundColor: theme.cssEnv.palette.secondary,
        color: '#ffffff',
        fontWeight: theme.cssEnv.typo.weightRegular,
        fontSize: '1rem',
        border: 'none',
        cursor: 'pointer',
      },
    '& .disabled': {
      display: 'flex',
      flexFlow: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      width: '100%',
      height: '2rem',
      borderStyle: 'solid',
      borderWidth: '1px',
      borderColor: theme.cssEnv.palette.secondary,
      color: theme.cssEnv.palette.secondary,
      fontWeight: theme.cssEnv.typo.weightRegular,
      fontSize: '1rem',
    },
  },
}))

export default useStyles